.PHONY: clean All

All:
	@echo "----------Building project:[ script - Debug ]----------"
	@"$(MAKE)" -f  "script.mk"
clean:
	@echo "----------Cleaning project:[ script - Debug ]----------"
	@"$(MAKE)" -f  "script.mk" clean
